version: "3.3"

services:
  build-prod:
    build: .
    volumes:
      - ./_site:/_site
    command: "yarn build-prod"
    depends_on:
      - build-css-prod

  build-css-prod:
    build: .
    volumes:
      - ./_site:/_site
    command: "yarn build-css-prod"

  site-dev:
    build: .
    volumes:
      - ./project:/project
      - ./_site:/_site
    ports:
      - "8080:8080"
    command: "yarn dev-serve"
    depends_on:
      - build-css-dev

  build-css-dev:
    build: .
    volumes:
      - ./project:/project
      - ./_site:/_site
    command: "yarn build-css-dev"

